In [18]:
import numpy as np
import pandas as pd

In [19]:
customer_insurance_df = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program\Week 4/Lab_7_Customer_insurance_file.csv")

In [20]:
customer_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [23]:
#Replacing the column label for uniformity in the dataset
customer_insurance_df = customer_insurance_df.rename(columns={"Customer":"customer",
                                                              "ST" : "state", 
                                                              "GENDER" : "gender",
                                                              "Education": "education",
                                                              "Customer Lifetime Value": "customer_lifetime_value",
                                                              "Income" : "income",
                                                              "Monthly Premium Auto" : "monthly_premium_auto",
                                                              "Number of Open Complaints": "number_of_open_complaints",
                                                              "Policy Type" : "policy_type",
                                                              "Vehicle Class": "vehicle_class",
                                                              "Total Claim Amount":" total_claim_amount"                                                        
                                                             })
customer_insurance_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', ' total_claim_amount'],
      dtype='object')

In [24]:
customer_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10   total_claim_amount        1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

Exercise 2: Cleaning invalid Values
The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

Hint:

Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".
State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"
In education, "Bachelors" could be replaced by "Bachelor"
In Customer Lifetime Value, delete the % character
In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"

In [26]:
customer_insurance_df["gender"].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [27]:
customer_insurance_df["gender"] = customer_insurance_df["gender"].replace ({'Femal':'F',
                                                                            'Male': 'M',
                                                                            'female' : 'F'})

In [28]:
customer_insurance_df["gender"].unique()

array([nan, 'F', 'M'], dtype=object)

In [29]:
customer_insurance_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [30]:
customer_insurance_df["state"] = customer_insurance_df["state"].replace ({'AZ':'Arizona',
                                                                          'WA':'Washington',
                                                                          'Cali':'California'})

In [31]:
customer_insurance_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [32]:
customer_insurance_df["education"].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [34]:
customer_insurance_df["education"] = customer_insurance_df["education"].replace ({'Bachelors':'Bachelor'})

In [35]:
customer_insurance_df["education"].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [36]:
customer_insurance_df["customer_lifetime_value"].unique()

array([nan, '697953.59%', '1288743.17%', ..., '2031499.76%', '323912.47%',
       '899704.02%'], shape=(1028,), dtype=object)

In [38]:
customer_insurance_df.loc[:,"customer_lifetime_value"] = (customer_insurance_df["customer_lifetime_value"].str.replace('%', ''))

In [39]:
customer_insurance_df["customer_lifetime_value"].unique()

array([nan, '697953.59', '1288743.17', ..., '2031499.76', '323912.47',
       '899704.02'], shape=(1028,), dtype=object)

In [40]:
customer_insurance_df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [41]:
customer_insurance_df["vehicle_class"] = customer_insurance_df["vehicle_class"].replace ({'Luxury SUV':"Luxury",
                                                                          'Sports Car':"Luxury",
                                                                          'Luxury Car':"Luxury"})

In [42]:
customer_insurance_df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

Exercise 3: Formatting data types
The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

Hint:

Customer lifetime value should be numeric
Number of open complaints has an incorrect format. Look at the different values it takes with unique() and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use split() to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.

In [44]:
clean_customer_insurance_df = customer_insurance_df

In [47]:
clean_customer_insurance_df = clean_customer_insurance_df.copy()

In [51]:
clean_customer_insurance_df.loc[:,"customer_lifetime_value"] = (clean_customer_insurance_df["customer_lifetime_value"].astype(str).str.replace(',', '').str.replace('%', '').astype(float))

clean_customer_insurance_df["customer_lifetime_value"] = pd.to_numeric(
    clean_customer_insurance_df["customer_lifetime_value"],
    errors='coerce')

In [52]:
clean_customer_insurance_df.dtypes

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
 total_claim_amount          float64
dtype: object

In [55]:
clean_customer_insurance_df['number_of_open_complaints'] = (clean_customer_insurance_df['number_of_open_complaints'].astype(str) .str.split('/').str[0].str.strip())

In [56]:
clean_customer_insurance_df['number_of_open_complaints'] = pd.to_numeric(clean_customer_insurance_df['number_of_open_complaints'],errors='coerce')

In [57]:
clean_customer_insurance_df['number_of_open_complaints'] = (clean_customer_insurance_df['number_of_open_complaints'].astype('Int64'))

In [58]:
clean_customer_insurance_df.dtypes

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      Int64
policy_type                   object
vehicle_class                 object
 total_claim_amount          float64
dtype: object

Exercise 4: Dealing with Null values
Identify any columns with null or missing values. Identify how many null values each column has. You can use the isnull() function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

Drop the rows or columns with null values
Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
Fill the null values with the previous or next value in the column
Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)
Implement your chosen strategy to handle the null values. You can use the fillna() function in pandas to fill null values or dropna() function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the isnull() function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [60]:
clean_customer_insurance_df.isnull().sum()

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
 total_claim_amount          2937
dtype: int64

In [61]:
#Dropping rows with null values
print("Before dropna:", clean_customer_insurance_df.shape)

Before dropna: (4008, 11)

In [80]:
clean_customer_insurance_df.tail(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
3998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
3999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN

In [ ]:
#dataset includes a several blank rows at the bottom of the file.Thus removed rows by comparing it with row that had all cells complete.

In [63]:
formatted_customer_insurance_df = clean_customer_insurance_df.dropna(subset=["customer"])
formatted_customer_insurance_df

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,California,F,High School or Below,2031499.76,63209.0,102.0,1,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,1,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11,79487.0,114.0,1,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02,54230.0,112.0,1,Personal Auto,Two-Door Car,537.600000

In [64]:
print("After dropna :", formatted_customer_insurance_df.shape)

After dropna : (1071, 11)

In [65]:
formatted_customer_insurance_df.isnull().sum()

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
 total_claim_amount            0
dtype: int64

In [67]:
formatted_customer_insurance_df[formatted_customer_insurance_df["gender"].isnull()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934
11,VQ65197,California,NaN,College,819719.71,0.0,110.0,1,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70,77026.0,110.0,1,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89,99845.0,110.0,1,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17,83689.0,70.0,1,Corporate Auto,Four-Door Car,307.139132
...,...,...,...,...,...,...,...,...,...,...,...
134,BU44523,Arizona,NaN,High School or Below,802637.96,0.0,74.0,1,Corporate Auto,Four-Door Car,532.800000
135,MS41162,Arizona,NaN,High School or Below,402296.35,0.0,117.0,1,Personal Auto,SUV,975.107098
136,PU25891,Oregon,NaN,High School or Below,961831.09,80536.0,119.0,1,Special Auto,Luxury,53.798708
138,SX26335,Oregon,NaN,College,955292.69,97732.0,79.0,1,Personal Auto,Four-Door Car,289.912200
449,LN31673,Washington,NaN,College,1131808.98,38923.0,99.0,1,Personal Auto,Four-Door Car,115.728852

In [70]:
formatted_customer_insurance_df = formatted_customer_insurance_df.copy()

In [71]:
formatted_customer_insurance_df["gender"] = formatted_customer_insurance_df["gender"].fillna("Unknown")

In [72]:
formatted_customer_insurance_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      3
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
 total_claim_amount          0
dtype: int64

In [74]:
median_customer_lifetime_value = formatted_customer_insurance_df["customer_lifetime_value"].median()
print("Median:", median_customer_lifetime_value)

Median: 588174.235

In [76]:
Cleaned_customer_insurance_df = formatted_customer_insurance_df.fillna({"customer_lifetime_value":median_customer_lifetime_value})

# Verify: no more nulls in Customer Lifetime Value
print("Nulls in Customer Lifetime Value after fillna:", formatted_customer_insurance_df["customer_lifetime_value"].isnull().sum())
print("Total rows :", Cleaned_customer_insurance_df.shape[0])

Nulls in Customer Lifetime Value after fillna: 3
Total rows : 1071

In [77]:
Cleaned_customer_insurance_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
 total_claim_amount          0
dtype: int64

Exercise 5: Dealing with duplicates
Use the .duplicated() method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:

Dropping all duplicate rows
Keeping only the first occurrence of each duplicated row
Keeping only the last occurrence of each duplicated row
Dropping duplicates based on a subset of columns
Dropping duplicates based on a specific column
Implement your chosen strategy using the drop_duplicates() function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using .duplicated().

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

Hint: after dropping duplicates, reset the index to ensure consistency.

In [79]:
Cleaned_customer_insurance_df.duplicated().sum()

np.int64(0)

In [ ]:
#Zero duplicates identified.

In [81]:
Cleaned_customer_insurance_df.to_csv("C:/Users/Winifred/Ironhack/Part time program\Week 4/Lab_7_Customer_insurance_file_solved.csv", index=False)

In [ ]:
clean_customer_insurance_df[["total_claim_amount", "customer_lifetime_value"]].describe()